config/routes.rb
Inspection::Application.routes.draw do
  get "monitor/live"

  resources :tasks

  resources :schedules_histories

  resources :routes_histories

  get "mobile_services/get_driver_schedule"
  get "mobile_services/get_driver_info"
  get "mobile_services/index"
  get "mobile_services/routes"
  post "mobile_services/routes" 

  resources :cabins

  resources :brakes_systems

  resources :compactor_drawers

  resources :electrical_systems

  resources :drive_systems

  resources :hydraulic_systems

  resources :bills

  resources :clients

  get "client_branches/get_client_branches"
  resources :client_branches

  resources :schedules

  resources :drivers

  resources :cellphones

  resources :trucks

  resources :error_reports

  resources :roles

  resources :branches

  resources :companies

  get "welcome/index"

  devise_for :users

  resources :users

  match 'companies/:company_id/users/:id/admin_edit' => 'users#admin_edit', :as => :admin_edit_user 
  devise_for :users

  devise_scope :user do
    get "devise/sessions/sing_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get 'devise/registrations/:id/edit' => 'devise/registrations#edit'#, :as => :edit_user_registration
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
  end

  root :to => 'welcome#index'

end

app/models/cellphone.rb
class Cellphone < ActiveRecord::Base
  belongs_to :user
  belongs_to :branch
  belongs_to :company
  attr_accessible :brand, :color, :condition, :description, :imei, :model, :ope_system, :phone_number, :user_id, :branch_id, :company_id
  validates :brand, :model, :imei, :branch_id, :presence => true
  self.per_page = 10
end

app/controllers/cellphones_controller.rb
class CellphonesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_data, :except => [:show, :destroy]
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cellphones }

    end
  end

  # GET /cellphones/1
  # GET /cellphones/1.json
  def show
    @cellphone = Cellphone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cellphone }
    end
  end

  # GET /cellphones/new
  # GET /cellphones/new.json
  def new
    @cellphone = Cellphone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cellphone }
    end
  end

  # GET /cellphones/1/edit
  def edit
    @cellphone = Cellphone.find(params[:id])
  end

  # POST /cellphones
  # POST /cellphones.json
  def create
    @cellphone = Cellphone.new(params[:cellphone])

    respond_to do |format|
      if @cellphone.save
        format.html { redirect_to @cellphone, notice: 'Cellphone was successfully created.' }
        format.json { render json: @cellphone, status: :created, location: @cellphone }
      else
        format.html { render action: "new" }
        format.json { render json: @cellphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cellphones/1
  # PUT /cellphones/1.json
  def update
    @cellphone = Cellphone.find(params[:id])

    respond_to do |format|
      if @cellphone.update_attributes(params[:cellphone])
        format.html { redirect_to @cellphone, notice: 'Cellphone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cellphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cellphones/1
  # DELETE /cellphones/1.json
  def destroy
    @cellphone = Cellphone.find(params[:id])
    @cellphone.destroy

    respond_to do |format|
      format.html { redirect_to cellphones_url }
      format.json { head :no_content }
    end
  end
  
  def get_data
    cellphones
    users
    branches
    companies
  end
  
end

app/helpers/cellphones_helper.rb
module CellphonesHelper
end

app/views/cellphones/_form.html.erb
<%= render "layouts/first_tab" %>
<%= form_for(@cellphone) do |f| %>
  <% if @cellphone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cellphone.errors.count, "error") %> prohibited this cellphone from being saved:</h2>

      <ul>
        <% @cellphone.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :model %>
    <%= f.text_field :model, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :color %>
    <%= f.text_field :color, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :ope_system %>
    <%= f.text_field :ope_system, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :condition %>
    <%= f.text_area :condition, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :imei %>
    <%= f.text_field :imei, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class=>"text-input small-input" %>
  </p>
  <p class="field">
    <%= f.label :user_id %>
    <%= f.collection_select(:user_id, @users, :id, :fullname, {:prompt => true}, :class =>'.small-input')%>
  </p>
  <p class="field">
    <%= f.label :company_id %>
    <%= f.collection_select(:company_id, @companies, :id, :name, {:prompt => session[:promp_company]}, :class =>'.small-input')%>
  </p>
  <p class="field">
    <%= f.label :branch_id %>
    <%= f.collection_select(:branch_id, @branches, :id, :name, {:prompt => session[:promp_branch]}, :class =>'.small-input')%>
  </p>

  <div class="form-actions">
    <%= f.submit nil, :class => 'button custom-submit' %>
  </div>
<% end %>
<div>
  <%= render "layouts/action_links" %>
</div>
<br><br><br>

app/views/cellphones/_tab_index.html.erb
<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
  <table>
    <thead>
      <tr>
        <th><input class="check-all" type="checkbox" /></th>
        <th><%= t'.id' %></th>
        <th><%= t'.phone_number' %></th>
        <th><%= t'.model' %></th>
        <th><%= t'.brand' %></th>
        <th><%= t'.imei' %></th>
        <th><%= t'.user' %></th>
      </tr>

    </thead>

    <tfoot>
      <tr>
        <td colspan="6">
          <div class="bulk-actions align-left">
            <%= render "layouts/select_action" %>
          </div>
          <%= render "layouts/pagination" %>
          <div class="clear"></div>
        </td>
      </tr>
    </tfoot>

    <tbody>
      <% @cellphones.each do |cellphone| %>
        <tr>
          <td><input type="checkbox" /></td>
          <%if can? :show, Cellphone %>
            <td><%=link_to cellphone.id, cellphone, :class => 'button'%></td>
          <%else%>
            <td><%= label cellphone.id, cellphone.id, :class => 'button'%></td>
          <%end%>


          <% @model = cellphone %> 

          <td><%= cellphone.phone_number %></td>

          <td><%= cellphone.model %></td>

          <td><%= cellphone.brand %></td>

          <td><%= cellphone.imei %></td>

          <%unless cellphone.user.blank?%>
            <td><%= cellphone.user.fullname %></td>
          <%else%>
            <td><%= link_to  "Asignar Celular a Usuario", edit_cellphone_path(cellphone)%></td>
          <%end%>

          <%= render "layouts/index_links" %>
        <% end %>
      </tr>
    </tbody>
  </table>
  <%= render "layouts/action_links" %>
</div> 

app/views/cellphones/edit.html.erb
<%= render 'form' %>

app/views/cellphones/index.html.erb
<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
  <table>
    <thead>
      <tr>
        <th><input class="check-all" type="checkbox" /></th>
        <th><%= t'.id' %></th>
        <th><%= t'.phone_number' %></th>
        <th><%= t'.model' %></th>
        <th><%= t'.brand' %></th>
        <th><%= t'.imei' %></th>
        <th><%= t'.user' %></th>
      </tr>

    </thead>

    <tfoot>
      <tr>
        <td colspan="6">
          <div class="bulk-actions align-left">
            <%= render "layouts/select_action" %>
          </div>
          <%= render "layouts/pagination" %>
          <div class="clear"></div>
        </td>
      </tr>
    </tfoot>

    <tbody>
      <% @cellphones.each do |cellphone| %>
        <tr>
          <td><input type="checkbox" /></td>
          <%if can? :show, Cellphone %>
            <td><%=link_to cellphone.id, cellphone, :class => 'button'%></td>
          <%else%>
            <td><%= label cellphone.id, cellphone.id, :class => 'button'%></td>
          <%end%>


          <% @model = cellphone %> 

          <td><%= cellphone.phone_number %></td>

          <td><%= cellphone.model %></td>

          <td><%= cellphone.brand %></td>

          <td><%= cellphone.imei %></td>

          <%unless cellphone.user.blank?%>
            <td><%= cellphone.user.fullname %></td>
          <%else%>
            <td><%= link_to  "Asignar Celular a Usuario", edit_cellphone_path(cellphone)%></td>
          <%end%>

          <%= render "layouts/index_links" %>
        <% end %>
      </tr>
    </tbody>
  </table>
  <%= render "layouts/action_links" %>
</div> 
<%= render "layouts/second_tab" %>
<br><br><br>

app/views/cellphones/new.html.erb
<%= render 'form' %>

app/views/cellphones/show.html.erb
<%= render "layouts/first_tab" %>

<div class="CSSTableGenerator" >
  <table >
    <tr>
      <td>
        <b><%= t'.phone_number' %></b> <%= @cellphone.phone_number %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.model' %></b> <%= @cellphone.model %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.brand' %></b> <%= @cellphone.brand %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.color' %></b> <%= @cellphone.color %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.ope_system' %></b> <%= @cellphone.ope_system %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.condition' %></b> <%= @cellphone.condition %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.imei' %></b> <%= @cellphone.imei %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.description' %></b> <%= @cellphone.description %>
      </td>
    </tr>
    <tr>     
      <%unless @cellphone.user.blank?%>
        <td>
          <b><%= t'.user_id' %></b> <%= @cellphone.user.fullname %>         
        </td>
      <%else%>
        <td>
          <b><%= t'Celular NO asignado' %></b> <%= link_to  "Asignar Celular a Usuario", edit_cellphone_path(@cellphone)%>
        </td>      
      <%end%>
    </tr>
    <tr>
      <td>
        <b><%= t'.branch_id' %></b> <%= @cellphone.branch.name %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%= t'.company_id' %></b> <%= @cellphone.company.name %>
      </td>
    </tr>
  </table>
  <%= render "layouts/action_links" %>
</div>
<br />